theme: jekyll-theme-minimal
plugins:
  - jekyll-last-modified-at   # plugins can be loaded if it's in whitelist, this is not in.
  - jekyll-commonmark-ghpages
  - jekyll-gfm-admonitions
markdown: CommonMarkGhPages
commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "-xxx-tagfilter"]
kramdown:
  syntax_highlighter_opts:
    guess_lang: true
timezone: 'Asia/Tokyo'


title: 
description: 
show_downloads: false
google_analytics:   # hard-coded in default.html
favicon:
logo_src:
logo_href: 
logo_background: 


defaults:
  - scope:
      path: ""   # an empty string here means all files in the project
    values:
      layout: "default"
      author:
        - "@SatorImaging"
