theme: jekyll-theme-minimal
title: 
description: 
show_downloads: false
google_analytics: 
plugins:
  - jekyll-last-modified-at
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      author:
        - "Sator Imaging"
