theme: jekyll-theme-minimal
plugins:
  - jekyll-last-modified-at # plugins can be loaded if it's in whitelist, this is not in.
kramdown:
  syntax_highlighter_opts:
    guess_lang: true

title: 
description: 
show_downloads: false
google_analytics: 
favicon: "https://www.sator-imaging.com/favicon.ico"
logo_src: "https://avatars.githubusercontent.com/u/45192683"
logo_href: 
logo_background: 

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      author:
        - "Sator Imaging"
