name: static import

on:
  schedule:
  - cron: '0 0,12 * * *'

  workflow_dispatch:

env:
  # listed in precedence order
  GH_TOKEN: ${{ github.token }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '10.0.x' ]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Install
      run: |
        dotnet tool install SatorImaging.DotnetTool.StaticImport -g --prerelease

    - name: Env
      run: |
        env

    - name: Migrate
      run: |
        git config --global user.name  "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        # プッシュしたら自動的にリモートリポジトリを追跡するように設定する
        git config --global --add --bool push.autoSetupRemote true


        git fetch

        BRANCH=static-import

        ## リポジトリのスイッチに失敗したら新しく作る（-c）
        #git switch ${BRANCH} || git switch -c ${BRANCH}

        ## リモートからプル（新しく作った場合は失敗するので || true する）
        #git pull || true


        ### main ###

        REPO=AppWindowUtility
        mkdir -p ${REPO} && pushd $_
          static-import -f -i  \
            "github:sator-imaging@${REPO}/main/README.md"  \
            "github:sator-imaging@${REPO}/main/README.ja.md"
        popd

        REPO=CSharp-TarArchiver
        mkdir -p ${REPO} && pushd $_
          static-import -f -i  \
            "github:sator-imaging@${REPO}/main/README.md"
        popd

        REPO=Copy-to-Another-Repository
        mkdir -p ${REPO} && pushd $_
          static-import -f -i  \
            "github:sator-imaging@${REPO}/main/README.md"
        popd

        REPO=FastOcean-Unity
        mkdir -p ${REPO} && pushd $_
          static-import -f -i  \
            "github:sator-imaging@${REPO}/main/README.md"
        popd


        git add **/*

        # 失敗しても全部正常終了させる！
        git commit -m "Static Import" || true
        git push || true
        gh pr create -B main -t '${BRANCH}' -b '' || true
